// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0elI17RoAIdDvssomBIEBmtGLwS7q8OE',
    appId: '1:402516449261:web:f40825e2428a33715df9e4',
    messagingSenderId: '402516449261',
    projectId: 'ecommerc-app-b83b4',
    authDomain: 'ecommerc-app-b83b4.firebaseapp.com',
    storageBucket: 'ecommerc-app-b83b4.firebasestorage.app',
    measurementId: 'G-BDFGJ4V6GW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL139-GlKdNqlY-Ck0IJvHxX7B3rIZufw',
    appId: '1:402516449261:android:2fc168461f9c90755df9e4',
    messagingSenderId: '402516449261',
    projectId: 'ecommerc-app-b83b4',
    storageBucket: 'ecommerc-app-b83b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA2qH5t3tEWRURUhxoEb4wlO6CXVh5Tic',
    appId: '1:402516449261:ios:a7f638d9324053365df9e4',
    messagingSenderId: '402516449261',
    projectId: 'ecommerc-app-b83b4',
    storageBucket: 'ecommerc-app-b83b4.firebasestorage.app',
    androidClientId: '402516449261-6cp70tpb8anm6im87r8k9h0lj4lomp7v.apps.googleusercontent.com',
    iosClientId: '402516449261-2b321kboudaan3pdp28jjeljsv1r0co9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomercAppWithAdmin',
  );

}